services:
  # This defines our Spring Boot backend service
  - type: web
    name: travelwise-backend
    env: java
    plan: free # Use the free instance type
    buildCommand: "./mvnw clean install -DskipTests"
    startCommand: "java -jar target/travelmanagementsystem-0.0.1-SNAPSHOT.jar"
    healthCheckPath: /api/packages
    envVars:
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT # Set the dialect for PostgreSQL
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: travelwise-db
          property: connectionString
      # We will add our secret API keys in the Render dashboard later
      - key: STRIPE_SECRET_KEY
        sync: false 
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENWEATHERMAP_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false

  # This defines our PostgreSQL database service
  - type: psql
    name: travelwise-db
    plan: free # Use the free database plan